services:
  - type: web
    name: splitnest-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: splitnest-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "20.11.1"

databases:
  - name: splitnest-db
    databaseName: splitnest
    user: splitnest_user
